version: "3.3"

volumes:
    redis-node1: {}
    redis-node2: {}
    redis-node3: {}
    redis-node4: {}
    redis-node5: {}
    redis-node6: {}

networks:
  redis-net:
    external: true

services:
  redis-node1:
    image: adrianriobo/redis-cluster:4.0.2-alpine
    networks:
      - redis-net
    volumes:
      - redis-node1:/data
    environment:
      - NODE_NAME=redis-node1
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  redis-node2:
    image: adrianriobo/redis-cluster:4.0.2-alpine
    networks:
      - redis-net
    volumes:
      - redis-node2:/data
    environment:
      - NODE_NAME=redis-node2
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  redis-node3:
    image: adrianriobo/redis-cluster:4.0.2-alpine
    networks:
      - redis-net
    volumes:
      - redis-node3:/data
    environment:
      - NODE_NAME=redis-node3
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  redis-node4:
    image: adrianriobo/redis-cluster:4.0.2-alpine
    networks:
      - redis-net
    volumes:
      - redis-node4:/data
    environment:
      - NODE_NAME=redis-node4
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  redis-node5:
    image: adrianriobo/redis-cluster:4.0.2-alpine
    networks:
      - redis-net
    volumes:
      - redis-node5:/data
    environment:
      - NODE_NAME=redis-node5
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  redis-node6:
    image: adrianriobo/redis-cluster:4.0.2-alpine
    networks:
      - redis-net
    volumes:
      - redis-node6:/data
    environment:
      - NODE_NAME=redis-node6
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
